# Site settings
title: Weiwei Xu
description: "be courageous"
url: "https://weiweihsu.github.io"

# Author
author:
  name: Weiwei Xu
  url: https://weiweihsu.com
  email: wei@weiweihsu.com
  drink: water

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
    # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5
paginate_path: "pages/weeknotes/page:num/"

# Collections
collections:
